### ISSUE TITLE
Mac上运行 gulp 命令打包生成static 报错 如下

### ISSUE THREAD

**Issue by yuchen931201** [oukingtim/king-admin#4]
java用了lombok注解简化代码，请下载lombok插件 如果不前后端分离部署，可以cd king-admin-angularjs 运行 gulp 命令打包生成static 然后替换到java或kotlin的resource里
`Error: Cannot find module 'wrench'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/tianzhen/MyFiles/MyWorkFiles/Java_WEB/Code/后台管理1漂亮/king-admin-master/king-admin-angularjs/gulpfile.js:4:14)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)`
我以前不是做javaweb的,刚开始学后台,所以还停留在用intellij或eclipse写代码运行的这种思维上, 而楼主的代码却能直接运行, 我很奇怪都没有启动servlet容器,甚至电脑上都没安装任何web服务器, 这个网页是如何运行在2000端口的呢?
我只希望将代码能导入到intellij中运行, 打包出war, 然后发布到jetty服务器中去...求楼主赐教

**Comment by oukingtim** [comment]
你这个报错是没有下载nodejs的module；
先安装nodejs；
npm install -g gulp cnpm bower
cnpm install
bower install
gulp serve；
默认pom.xml是springboot的jar运行，打war包用pom-war.xml
